SystemUI: ActivityManagerWrapper: Add missing method for pixel launcher
Hellow! This commit is scheduled by DerpFest to be leeched. :)

Log:
09-22 00:57:22.509  4085  4118 E AndroidRuntime: FATAL EXCEPTION: UiThreadHelper
09-22 00:57:22.509  4085  4118 E AndroidRuntime: Process: com.google.android.apps.nexuslauncher, PID: 4085
09-22 00:57:22.509  4085  4118 E AndroidRuntime: java.lang.NoSuchMethodError: No interface method preloadRecentsActivity(Landroid/content/Intent;)V in class Landroid/app/IActivityTaskManager; or its super classes (declaration of 'android.app.IActivityTaskManager' appears in /system/framework/framework.jar)
09-22 00:57:22.509  4085  4118 E AndroidRuntime: 	at com.android.systemui.shared.system.ActivityManagerWrapper.preloadRecentsActivity(go/retraceme 75b8c5afe2811cd3fc83975ee085910b2b768d76f3bb50002eb01a94df5031e4:5)
09-22 00:57:22.509  4085  4118 E AndroidRuntime: 	at com.android.quickstep.TaskAnimationManager.lambda$preloadRecentsAnimation$0(go/retraceme 75b8c5afe2811cd3fc83975ee085910b2b768d76f3bb50002eb01a94df5031e4:5)
09-22 00:57:22.509  4085  4118 E AndroidRuntime: 	at com.android.quickstep.TaskAnimationManager.a(go/retraceme 75b8c5afe2811cd3fc83975ee085910b2b768d76f3bb50002eb01a94df5031e4:1)
09-22 00:57:22.509  4085  4118 E AndroidRuntime: 	at com.android.quickstep.j1.run(go/retraceme 75b8c5afe2811cd3fc83975ee085910b2b768d76f3bb50002eb01a94df5031e4:22)
09-22 00:57:22.509  4085  4118 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:959)
09-22 00:57:22.509  4085  4118 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
09-22 00:57:22.509  4085  4118 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
09-22 00:57:22.509  4085  4118 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
09-22 00:57:22.509  4085  4118 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:85)

Signed-off-by: Pranav Vashi <neobuddy89@gmail.com>